calendar: don't decorate requests with $activity
This leads to non-standard LS2 calls, which conflicts with schema checks.
Fixes message like the following:
Error: invalid parameters: caller='com.palm.app.calendar' error='property not allowed - '$activity''

Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>